// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var DAILY_COUNT, DECK_COUNT_SQL, DECK_QUERY_SQL, HISTORY_COUNT_SQL, HISTORY_QUERY_SQL, PAGE_LIMIT, custom_commands, dailyCount, fs, mycardPool, queryDeck, queryDeckCount, queryHistory, queryHistoryCount, runCommands, setCommands, standardPromiseCallback, standardQueryCallback, ygoproPool;

  ({mycardPool, ygoproPool, standardQueryCallback, standardPromiseCallback} = require('./database'));

  custom_commands = require('./analytics.json');

  fs = require('fs');

  PAGE_LIMIT = 100;

  HISTORY_QUERY_SQL = `select * from battle_history where (usernamea like $1::text or usernameb like $1::text) and type like $2::text order by start_time desc limit ${PAGE_LIMIT} offset $3`;

  HISTORY_COUNT_SQL = "select count(*) from battle_history where (usernamea like $1::text or usernameb like $1::text) and type like $2::text";

  DECK_QUERY_SQL = `select * from deck_day where (name like $1::text and source like $2::text) order by time desc, count desc, source desc limit ${PAGE_LIMIT} offset $3`;

  DECK_COUNT_SQL = "select count(*) from deck_day where name like $1::text and source like $2::text";

  DAILY_COUNT = 'SELECT day, sum(' + '      CASE' + '            WHEN sum_time < \'1 hour\' THEN 0' + '            WHEN sum_time < \'30 minute\' THEN 0.5' + '            ELSE 1' + '      END) AS day_active_users ' + 'FROM' + '      (SELECT username, sum(time_length) AS sum_time, day FROM' + '            (SELECT usernamea AS username, end_time - battle_history.start_time AS time_length, date_trunc(\'day\', start_time) as day' + '                  FROM battle_history' + '                  WHERE type like $1::text' + '                  UNION SELECT usernameb AS username, end_time - battle_history.start_time AS time_length, date_trunc(\'day\', start_time) as day' + '                        FROM battle_history' + '                        WHERE type like $1::text) as B' + '      GROUP BY username, day) as user_time ' + 'GROUP BY day ORDER BY day DESC LIMIT 100;';

  runCommands = function(callback) {
    var answer, command, i, len, promises, target_pool;
    answer = [];
    promises = [];
    for (i = 0, len = custom_commands.length; i < len; i++) {
      command = custom_commands[i];
      let name = command.name;
      target_pool = command.target === 'mycard' ? mycardPool : ygoproPool;
      promises.push(target_pool.query(command.query).then(function(result) {
        return answer.push({
          name: name,
          result: result.rows
        });
      }));
    }
    return Promise.all(promises).then(function() {
      return callback.call(this, answer);
    });
  };

  setCommands = function(commands) {
    custom_commands = commands;
    return fs.writeFile('./express-server/analytics.json', JSON.stringify(commands, null, 2), function() {});
  };

  queryHistory = function(name, type, start, callback) {
    if (type === 'all' || !type) {
      type = "%";
    }
    return ygoproPool.query(HISTORY_QUERY_SQL, [`%${name}%`, type, (start - 1) * PAGE_LIMIT], function(err, result) {
      if (err) {
        console.log(err);
        return callback.call(this, []);
      } else {
        return callback.call(this, result.rows);
      }
    });
  };

  queryHistoryCount = function(name, type, callback) {
    if (type === 'all' || !type) {
      type = "%";
    }
    return ygoproPool.query(HISTORY_COUNT_SQL, [`%${name}%`, type], function(err, result) {
      if (err) {
        console.log(err);
        return callback.call(this, 0);
      } else {
        return callback.call(this, Math.ceil(result.rows[0].count / PAGE_LIMIT));
      }
    });
  };

  queryDeck = function(name, source, start, callback) {
    return ygoproPool.query(DECK_QUERY_SQL, [`%${name}%`, `%${source}%`, start], function(err, result) {
      if (err) {
        console.log(err);
        return callback.call(this, []);
      } else {
        return callback.call(this, result.rows);
      }
    });
  };

  queryDeckCount = function(name, source, callback) {
    return ygoproPool.query(DECK_COUNT_SQL, [`%${name}%`, `%${source}%`], function(err, result) {
      if (err) {
        console.log(err);
        return callback.call(this, 0);
      } else {
        return callback.call(this, Math.ceil(result.rows[0].count / PAGE_LIMIT));
      }
    });
  };

  dailyCount = function(type) {
    return new Promise(function(resolve, reject) {
      if (!type || type === 'all') {
        type = '%';
      }
      return ygoproPool.query(DAILY_COUNT, [type], function(err, result) {
        return standardPromiseCallback(resolve, reject, err, result);
      });
    });
  };

  module.exports.queryHistory = queryHistory;

  module.exports.queryHistoryCount = queryHistoryCount;

  module.exports.runCommands = runCommands;

  module.exports.setCommands = setCommands;

  module.exports.queryDeck = queryDeck;

  module.exports.queryDeckCount = queryDeckCount;

  module.exports.dailyCount = dailyCount;

}).call(this);

//# sourceMappingURL=analytics.js.map
