// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var authorize, url;

  url = require('url');

  authorize = function(sso, sig) {
    var parsedUrl, query, text;
    if (!(sso && sig)) {
      return false;
    }
    text = new Buffer(sso, 'base64').toString();
    parsedUrl = url.parse("http://127.0.0.1?" + text, true);
    query = parsedUrl.query;
    return query.admin === 'true';
  };

  module.exports.authorize = authorize;

}).call(this);

//# sourceMappingURL=author.js.map
