// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var authorize, authorize_router, formatQuery, url;

  url = require('url');

  authorize = function(sso, sig) {
    var parsedUrl, query, text;
    if (!(sso && sig)) {
      return false;
    }
    text = new Buffer(sso, 'base64').toString();
    parsedUrl = url.parse("http://127.0.0.1?" + text, true);
    query = parsedUrl.query;
    if (query.admin === 'true') {
      return query.username;
    } else {
      return null;
    }
  };

  formatQuery = function(query) {
    var i, key, len, queries, ref;
    queries = [];
    ref = Object.keys(query);
    for (i = 0, len = ref.length; i < len; i++) {
      key = ref[i];
      if (key !== 'sso' && key !== 'sig' && query[key] !== "") {
        queries.push(`${key} = ${query[key]}`);
      }
    }
    if (queries.length === 0) {
      return "";
    } else {
      return ", " + queries.join(", ");
    }
  };

  authorize_router = function(req, res, next) {
    var sig, sso, username;
    sso = req.query.sso;
    sig = req.query.sig;
    if (username = authorize(sso, sig)) {
      console.log(`${username} - ${req.method} ${req._parsedUrl.pathname}${formatQuery(req.query)}`);
      return next();
    } else {
      res.statusCode = 403;
      return res.end("Not authorized");
    }
  };

  module.exports.authorize = authorize;

  module.exports.authorizeRouter = authorize_router;

}).call(this);

//# sourceMappingURL=author.js.map
