// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var authorize, authorize_router, url;

  url = require('url');

  authorize = function(sso, sig) {
    var parsedUrl, query, text;
    if (!(sso && sig)) {
      return false;
    }
    text = new Buffer(sso, 'base64').toString();
    parsedUrl = url.parse("http://127.0.0.1?" + text, true);
    query = parsedUrl.query;
    return query.admin === 'true';
  };

  authorize_router = function(req, res, next) {
    var sig, sso;
    sso = req.query.sso;
    sig = req.query.sig;
    if (authorize(sso, sig)) {
      return next();
    } else {
      res.statusCode = 403;
      return res.end("Not authorized");
    }
  };

  module.exports.authorize = authorize;

  module.exports.authorizeRouter = authorize_router;

}).call(this);

//# sourceMappingURL=author.js.map
