// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var Config, Pool;

  ({Pool} = require('pg'));

  Config = require('./config.json');

  module.exports.mycardPool = new Pool(Config.mycardDatabase);

  module.exports.ygoproPool = new Pool(Config.ygoproDatabase);

  module.exports.standardQueryCallback = function(err, result, callback) {
    if (err) {
      console.log(err);
      return callback.call(this, null);
    } else {
      return callback.call(this, result.rows);
    }
  };

  module.exports.standardPromiseCallback = function(resolve, reject, err, result) {
    if (err) {
      console.log(err);
      return reject(err);
    } else {
      return resolve(result.rows);
    }
  };

}).call(this);

//# sourceMappingURL=database.js.map
