// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var Config, Pool;

  ({Pool} = require('pg'));

  Config = require('./config.json');

  module.exports.mycardPool = new Pool(Config.mycardDatabase);

  module.exports.ygoproPool = new Pool(Config.ygoproDatabase);

}).call(this);

//# sourceMappingURL=database.js.map
