// Generated by CoffeeScript 2.0.1
(function() {
  var config, pack, refresh, request;

  config = require('./config.json');

  request = require('request');

  pack = function() {
    return Promise.new(function(resolve, reject) {
      var url;
      url = config.updateServer.packageHost + "pack?access_key=" + config.updateServer.password;
      return request.post(url, function(err, res, body) {
        return resolve('ok');
      });
    });
  };

  refresh = function() {
    return Promise.new(function(resolve, reject) {
      var url;
      url = config.updateServer.serverHost + "clear?access_key=" + config.updateServer.password;
      return request.post(url, function(err, res, body) {
        return resolve('ok');
      });
    });
  };

}).call(this);

//# sourceMappingURL=packager.js.map
