// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var format_time, moment, time_router;

  moment = require('moment');

  format_time = function(time) {
    if (!(time && time > 0)) {
      return null;
    }
    return moment(time);
  };

  time_router = function(req, res, next) {
    var end_time, start_time;
    start_time = parseInt(req.query.start_time);
    end_time = parseInt(req.query.end_time);
    req.start_time = format_time(start_time) || moment('1970-01-01 00:00:00');
    req.end_time = format_time(end_time) || moment();
    return next();
  };

  module.exports.timeRouter = time_router;

}).call(this);

//# sourceMappingURL=time.js.map
