// Generated by CoffeeScript 2.1.0
import React, {
  Component
} from 'react';

import {} from 'react-bootstrap';

export var MCProConsoleIdentifierCard = class MCProConsoleIdentifierCard extends Component {
  render() {
    var id;
    id = this.props.id;
    if (!id) {
      return null;
    }
    return <a href={"https://www.ourocg.cn/search/" + id.toString()}>
            <img src={"http://cdn.233.momobako.com/ygopro/pics/" + id.toString() + ".jpg!thumb"} alt="" target='_blank'></img>
        </a>;
  }

};

MCProConsoleIdentifierCard.defaultProps = {
  id: 0
};

export default MCProConsoleIdentifierCard;

//# sourceMappingURL=card.js.map
