// Generated by CoffeeScript 2.1.0
import React, {
  Component
} from 'react';

import {
  Panel
} from 'react-bootstrap';

import MCProConsoleIdentifierCard from "./card";

export var MCProConsoleIdentifierSet = class MCProConsoleIdentifierSet extends Component {
  render() {
    var set;
    set = this.props.set;
    if (!set) {
      return null;
    }
    return <Panel header={set.name + (set.originName && set.originName.length > 0 ? `[${set.originName}]` : "")}>
            {set.ids.map(function(id) {
      return <MCProConsoleIdentifierCard id={id} />;
    })}
        </Panel>;
  }

};

MCProConsoleIdentifierSet.defaultProps = {
  set: null
};

export default MCProConsoleIdentifierSet;
